# Positioning and Style
legacy_layout=0
horizontal
round_corners=5
# background_alpha=0
text_outline=1
horizontal_stretch=0
font_size=18
font_size_text=18
hud_no_margin
hud_compact

# Row 1: Frame Rate
fps

# Row 2: Active GPU
gpu_name

# Row 3: GPU Metrics
gpu_stats
gpu_temp

# Row 4: CPU Metrics
cpu_stats
cpu_temp

# Hotkeys
toggle_hud=Shift_R+F12
